version: '3.8'
services:
    db_3_2:
        image: postgres:latest
        container_name: postgres_container
        ports: 
            - 5435:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: currency
        volumes:
            - ./DDL/ddl_init.sql:/docker-entrypoint-initdb.d/ddl_init.sql

        healthcheck:
            test: ["CMD", "pg_isready", "-d", "currency", "-U", "postgres"]
            interval: 5s
            retries: 5
        restart: always
